### AIML: Introduction: numpy  (17th February 2022, Thursday)

Importing numpy

In [43]:
import numpy as np

arr = np.array([0, 1, 2])

Storing the data type of elements stored inside the array

In [44]:
arr.dtype

dtype('int32')

Explicitly declaring an Integer datatype

In [45]:
arr = np.array([0, 2, 1, 5, 2, 6], dtype='int')
print(arr)

- `numpy.arange(lowerlim, upperlim)`

In [47]:
arr = np.arange(0, 3)
print(arr)

[0 1 2]


In [48]:
# Array with 5 zeros 
arr = np.zeros(5, dtype='int')

print(arr)

[0 0 0 0 0]


- `numpy.reshape(row, column)`

In [49]:
a = np.arange(0, 4)
print(a)

b = a.reshape(2, 2)
print(b)

[0 1 2 3]
[[0 1]
 [2 3]]


Combining above expressions in 1 single line

In [50]:
arr = np.arange(0, 4).reshape(2, 2)
print(arr)

[[0 1]
 [2 3]]


Showing the shape of the array

In [51]:
print(f"The shape of the array is : {np.shape(arr)}")

The shape of the array is : (2, 2)


Type of shape object

In [52]:
type(np.shape(arr)[0])

int

Working with `np.average`

In [53]:
arr = np.array(range(10))
print(np.average(arr))

4.5


`numpy.mean()` -> actual average  
`numpy.average()` -> weighted average

In [54]:
arr = np.array(range(10))
print(np.average(arr, ))
print(np.mean(arr))

4.5
4.5


`numpy.add() function`

- Automatically typeCasts the 2 arrays

In [55]:
arr1 = np.array([9, 0, 7])
arr2 = np.array([1, 2, 3])

sum_arr = np.add(arr1, arr2)
print(sum_arr)

assert type(arr) is type(sum_arr)

[10  2 10]


In [56]:
num = 8 #int(input("Number: "))
print(f"Square root of {num} is {np.sqrt(num)}")

print(num**0.5)

Square root of 8 is 2.8284271247461903
2.8284271247461903
