### AIML: MLP: Multi Layer perception (13th April 2022, Wednesday)

In [1]:
from sklearn.datasets import load_breast_cancer

cancer_dataset = load_breast_cancer()

In [2]:
from sklearn.model_selection import train_test_split as tts

# Split the dataset, pass the train data
x_train, x_test, y_train, y_test = tts(cancer_dataset.data, cancer_dataset.target, test_size=.25)

Import the MLPClassifier

In [3]:
from sklearn.neural_network import MLPClassifier

Classifier = MLPClassifier(
    hidden_layer_sizes=(10, 100, 50),
    max_iter=300,
    activation='relu',  # relu: Rectified Linear Unit -> an activation function to realign nodes to 0 amd 1
    solver='adam',  # oprimizer for weight
    random_state=1  # simple state based on the seed initial data will be generated
)

Classifier.fit(x_train, y_train)


MLPClassifier(hidden_layer_sizes=(10, 100, 50), max_iter=300, random_state=1)

In [4]:
y_pred = Classifier.predict(x_test)

from sklearn.metrics import confusion_matrix

Cf_Matrix1 = confusion_matrix(
    y_test,  # <- Ground truth information fro my test data
    y_pred,  # <- Prediction given by the classifier
)
print(Cf_Matrix1)

# [39 11]    [   True Positive   | False Positive(FP)]
# [ 7 86]    [ False Negtive(FN) |    True Negative  ]


[[44 11]
 [ 1 87]]


In [5]:
import numpy as np
Cf_Matrix = np.transpose(
    np.transpose(Cf_Matrix1) / Cf_Matrix1.astype(float).sum(axis=1)
)
print(Cf_Matrix1)

[[44 11]
 [ 1 87]]


 PROBLEM: Perform the same experiment on the breast cancer dataset using Logistic Regression and DecisionTree Classification models. In each case, identify the confusion matrix and TP, TN, FP & FN. Finally, discuss which classifier is best suied for deploying as a real-time smart cancer diagnosis system

1. Using Logistic Regression

In [6]:
from sklearn.linear_model import LogisticRegression

LogReg1 = LogisticRegression(max_iter=10_000)
LogReg1.fit(x_train, y_train)

y_pred = LogReg1.predict(x_test)

Cf_Matrix2 = confusion_matrix(
    y_test,  # <- Ground truth information fro my test data
    y_pred,  # <- Prediction given by the classifier
)

print(Cf_Matrix2)

[[49  6]
 [ 3 85]]


2. Using Decision Tree Classifier

In [7]:
from sklearn.tree import DecisionTreeClassifier


DecTree1 = DecisionTreeClassifier(criterion='gini', max_depth=30)
DecTree1.fit(x_train, y_train)
y_pred = DecTree1.predict(x_test)

Cf_Matrix3 = confusion_matrix(
    y_test,   # <- Ground truth information fro my test data
    y_pred    # <- Prediction given by the classeifier
)

print(Cf_Matrix3)

[[52  3]
 [ 3 85]]


Comparing Results

In [8]:
#  MLP Classifier
print("MLP Classifier: ", Cf_Matrix1, sep='\n')

# Logistic Regression
print("Logistic Regression: ", Cf_Matrix2, sep='\n')

# Decision Tree Classifier
print("Decision Tree Classifier: ", Cf_Matrix3, sep='\n')


MLP Classifier: 
[[44 11]
 [ 1 87]]
Logistic Regression: 
[[49  6]
 [ 3 85]]
Decision Tree Classifier: 
[[52  3]
 [ 3 85]]
